apiVersion: v1
kind: Pod
metadata:
  name: scary
spec:
  hostNetwork: true
  hostPID: true
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/scary"
          name: localvol
          readOnly: false
      securityContext:
        privileged: true
  volumes:
    - name: localvol
      hostPath:
        path: "/"